import { chromium } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:3000');
await page.getByRole('heading', { name: /Prove what matters/ }).waitFor();
await mkdir('docs/screenshots', {recursive:true});
await page.screenshot({ path: 'docs/screenshots/overview.png', fullPage: true });
await page.getByRole('button', { name: 'Launch demo', exact: true }).click();
await page.getByLabel('Vault passphrase').fill('veilpass-test-passphrase');
await page.getByRole('button', { name: 'Get Demo Credential', exact: true }).click();
await page.getByRole('button', { name: 'Prove my eligibility' }).waitFor();
const stored = await page.evaluate(() => localStorage.getItem('veilpass.vault.v1'));
if (!stored || stored.includes('studentId') || stored.includes('graduationYear')) throw new Error('Vault encryption failed');
await page.screenshot({ path: 'docs/screenshots/credential.png', fullPage: true });
await page.getByRole('button', {name:'Lock vault',exact:true}).click();
await page.getByLabel('Vault passphrase').fill('wrong-passphrase');
await page.getByRole('button',{name:'Unlock private vault'}).click();
await page.getByRole('alert').filter({hasText:'Could not unlock'}).waitFor();
await page.getByLabel('Vault passphrase').fill('veilpass-test-passphrase');
await page.getByRole('button',{name:'Unlock private vault'}).click();
await page.getByRole('button',{name:'Prove my eligibility'}).click();
await page.getByRole('button',{name:'Connect wallet to continue'}).click();
await page.getByRole('heading',{name:'No Midnight wallet detected'}).waitFor();
await page.getByRole('button',{name:'Close wallet selection'}).click();
await page.screenshot({path:'docs/screenshots/verification.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Overview',exact:true}).click();
if(await page.evaluate(()=>document.documentElement.scrollWidth > innerWidth)) throw new Error('Mobile overflow');
await page.screenshot({path:'docs/screenshots/mobile.png',fullPage:true});
await browser.close();
if(errors.length) throw new Error(errors.join('\n'));
console.log('UI checks passed: issuance, encrypted persistence, wrong-passphrase rejection, unlock, wallet-missing state, mobile layout.');
